### ISSUE TITLE
Cleaner front page

### ISSUE THREAD

**Issue by drazisil** [namecoin/namecoin.info-dotbit#9]
Current front page is taken 50% by an image, and the other by a wall of text.

As I understand, namecoin is (or was) designed to be a decentralized domain registrar.

The page seems to be mainly about freedom in the GNU sense and actually seems to tell very little about what the software is, or how to get started.

There is no call to action, or even an easy way to download (the download link being last on the nav bar, playing team, video and everything else above it in importance.

IMO, most of the front page should be moved to either features or philosophy.

The front page, 'above the fold' should be 'this is what it is, this is how to get started'

References bitcoin.org for a clean fast layout and call to action.
![selection_002](https://cloud.githubusercontent.com/assets/190986/9700534/352d19e8-53d4-11e5-862a-ea0e277fa071.png)

**Comment by phelixbtc** [comment]
Thank you very much for your feedback. Note we are currently in the process of creating a new base layer for the website: http://github.com/namecoin/namecoin.org  Larger design changes like this will have to wait until we have switched.

The previous website looked somewhat dull so this layout from a designer was quite an improvement.

The download link in particular is placed OK imho as the eye seems to stop at the last of the menu items.

Now that you point it out I must agree that the "call to action" is missing. I have created an issue for the new website: https://github.com/namecoin/namecoin.org/issues/34

The Namecoin team currently is lacking in marketing knowledge and experience so feedback like this helps.
